receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 100ms # Send fast
    send_batch_size: 512

  # Resource Enrichment (Simulating K8s Node)
  resource:
    attributes:
      - key: k8s.node.name
        value: "simulated-node-1"
        action: upsert
      - key: deployment.environment
        value: "local-dev"
        action: upsert

  # Data scrubbing (Security requirement - Shift Left)
  # Scrubbing at the agent prevents PII from ever leaving the node
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - replace_pattern(attributes["user.email"], ".*", "*****") where attributes["user.email"] != nil

exporters:
  # Forward to Gateway (Load Balanced in real K8s)
  otlp/gateway:
    endpoint: "otel-gateway:4317"
    tls:
      insecure: true

  debug:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, transform, batch]
      exporters: [otlp/gateway]
    
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/gateway]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      # Logs often go directly to backend in some archs, but for uniformity we send to Gateway
      exporters: [otlp/gateway]
