global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/prometheus_rules.yml"

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-gateway:8889']
      - targets: ['otel-gateway:8888'] # Gateway's own metrics
